Repository WildCodeSchool-2023-09/remfr-php-p3-babyplace, pull requests merged in 2024-01, with the labels that each got.

#16 Parent profil
  .gitignore
  assets/app.js
  assets/styles/app.scss
  assets/styles/parent/_navbar-parent.scss
  assets/styles/parent/register-parent.scss
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20240105082734.php
  package.json
  phpmd.xml
  src/Controller/AdministrationController.php
  src/Controller/FamilyController.php
  src/Controller/UserRegistrationController.php
  src/Entity/Administration.php
  src/Form/AdministrationType.php
  src/Form/FamilyType.php
  src/Form/UserRegistrationFormType.php
  templates/family/index.html.twig
  templates/home/index.html.twig
  templates/parent/_navbar-parent.html.twig
  templates/parent/register-parent.html.twig
  webpack.config.js
  yarn.lock
Labels: help wanted

#14 Logout
  .env
  .gitignore
  assets/app.js
  assets/styles/login.scss
  compose.override.yaml
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  config/packages/security.yaml
  docker-compose.yml
  migrations/Version20231221115738.php
  migrations/Version20231221120532.php
  migrations/Version20240103150958.php
  migrations/Version20240105090338.php
  package.json
  phpstan.dist.neon
  src/Controller/HomeController.php
  src/Controller/LoginController.php
  src/Controller/ResetPasswordController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Form/UserRegistrationFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  src/Security/UserAuthenticator.php
  symfony.lock
  templates/login.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
  yarn.lock
Labels: PROBLEM SOLVED

#24 Dossiers annexes
  assets/app.js
  assets/styles/app.scss
  assets/styles/parent/confirmation-inscription.scss
  assets/styles/parent/menu-parent.scss
  assets/styles/parent/profil-parent.scss
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20240105163416.php
  migrations/Version20240106141756.php
  migrations/Version20240106185310.php
  package.json
  script.sh
  src/Controller/ChildController.php
  src/Controller/EmergencyContactController.php
  src/Controller/FamilyController.php
  src/Entity/Child.php
  src/Entity/EmergencyContact.php
  src/Form/ChildType.php
  src/Form/EmergencyContactFormType.php
  src/Repository/EmergencyRepository.php
  templates/child/_delete_form.html.twig
  templates/child/_form.html.twig
  templates/child/edit.html.twig
  templates/child/index.html.twig
  templates/child/new.html.twig
  templates/child/show.html.twig
  templates/dashboard-creche.html.twig
  templates/emergency-contact/_delete_form.html.twig
  templates/emergency-contact/_form.html.twig
  templates/emergency-contact/edit.html.twig
  templates/emergency-contact/index.html.twig
  templates/emergency-contact/new.html.twig
  templates/emergency-contact/show.html.twig
  templates/emergency/index.html.twig
  templates/parent/_header-parent.html.twig
  templates/parent/confirmation-inscription.html.twig
  templates/parent/menu.html.twig
  templates/parent/profil-parent.html.twig
  yarn.lock
Labels: enhancement
